version: '3'
services:
  receiver:
    build:
      context: ./
      dockerfile: ./Dockerfile.receiver
    depends_on:
      - redis
  redis:
    image: 'redis:alpine'
    ports:
      - '127.0.0.1:6379:6379'
